# Generated by Django 3.2 on 2021-04-07 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('name', models.CharField(max_length=100, verbose_name='Họ và tên')),
                ('telephone', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('address', models.CharField(max_length=200, verbose_name='Địa chỉ')),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('nenkin_1_status', models.CharField(max_length=200, verbose_name='Nenkin 1')),
                ('nenkin_3_status', models.CharField(max_length=200, verbose_name='Nenkin 2')),
            ],
        ),
    ]
